on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        name: Install pnpm
        with:
          standalone: true
          cache: true

      - run: pnpm node -v

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: node -v

      - run: pnpm node -v

      - run: pnpm --filter a start

      - run: pnpm -r rebuild
        if: always()
      
      - run: pnpm --filter a start
        if: always()
