on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - run: curl -fsSL https://get.pnpm.io/install.sh | sh -
      - run: source /home/runner/.bashrc

      - run: pnpm node -v

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: node -v
      - run: which node

      - run: pnpm node -v

      - run: pnpm --filter a start

      - run: pnpm -r rebuild
        if: always()
      
      - run: pnpm --filter a start
        if: always()
